package com.example.hongcheng.common.db.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MESSAGE_INFO".
 */
public class MessageInfo {

    private Long id;
    private String msgId;
    private Double content;
    private Double title;
    private Double date;
    private Double params;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MessageInfo() {
    }

    public MessageInfo(Long id) {
        this.id = id;
    }

    public MessageInfo(Long id, String msgId, Double content, Double title, Double date, Double params) {
        this.id = id;
        this.msgId = msgId;
        this.content = content;
        this.title = title;
        this.date = date;
        this.params = params;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public Double getContent() {
        return content;
    }

    public void setContent(Double content) {
        this.content = content;
    }

    public Double getTitle() {
        return title;
    }

    public void setTitle(Double title) {
        this.title = title;
    }

    public Double getDate() {
        return date;
    }

    public void setDate(Double date) {
        this.date = date;
    }

    public Double getParams() {
        return params;
    }

    public void setParams(Double params) {
        this.params = params;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
