package com.example.hongcheng.common.db.dao;

import de.greenrobot.dao.AbstractDaoSession;
import android.database.sqlite.SQLiteDatabase;
import com.example.hongcheng.common.db.model.MessageInfo;
import java.util.Map;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageInfoDaoConfig;

    private final MessageInfoDao messageInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageInfoDaoConfig = daoConfigMap.get(MessageInfoDao.class).clone();
        messageInfoDaoConfig.initIdentityScope(type);

        messageInfoDao = new MessageInfoDao(messageInfoDaoConfig, this);

        registerDao(MessageInfo.class, messageInfoDao);
    }
    
    public void clear() {
        messageInfoDaoConfig.getIdentityScope().clear();
    }

    public MessageInfoDao getMessageInfoDao() {
        return messageInfoDao;
    }

}
